### ISSUE TITLE
The message for a pull request that is too large shows the wrong number

### ISSUE THREAD

**Issue by aerodynamica** [microsoft/PR-Metrics#255] opened 2022-09-21 22:43 UTC
## Summary

     
❌ Try to keep pull requests smaller than **x** lines...

x is not the same number as the number that is used too check the size
x equals the baseSize and the number to check is baseSize * 2

## Reproduction Steps

Use the default growthRate. Create a pull request with size between baseSize and baseSize * 2 (= small).
The message will be ❌ Try to keep pull requests smaller than **baseSize** lines...

## Additional Information

```
- task: PRMetrics@1
  displayName: PR Metrics
  env:
    PR_METRICS_ACCESS_TOKEN: $(PRmetrics)
  inputs:
    TestFactor: 0.0
    BaseSize: 50
    FileMatchingPatterns: |
      **/*
    CodeFileExtensions: |
      java
      xml
      html
      yaml
      jrxml
      txt
      meta
      sql
      js
      properties
      css
      xsd
      dlg
      yaml
      yml
      iml
  continueOnError: true  
```

**Comment by muiriswoulfe** [comment] 2022-10-04 15:19
Hi @aerodynamica, thanks for using PR Metrics and for filing this issue.

Unfortunately, I'm unable to reproduce it. When I try to reproduce it, I find that if the PR is Medium or larger, the message correctly specifies the base size. And if the PR is Small or Extra Small, the message doesn't contain a size.

Could you verify that you've completed a re-run of PR Metrics after any change to the PR, in case the results you provided are originating from an older run of the task? Afterwards, if you continue to encounter the issue, could you provide any additional details that might help to diagnose what is different on your system.

**Comment by aerodynamica** [comment] 2022-10-07 14:57
For a configuration with base-size = 50 and growth-factor = 2, you have the following sizes as a function of the number of lines changed:
0-49 lines: XS
50-99 lines: S
100-199 lines: M
200-399 lines: L
etc.

Now if you have a pull request with 70 lines of code changed, there will be no message. This is correct as the pull request is small (<100 lines).
But if you have a pull request with 140 lines of code changed, the message will be 
❌ Try to keep pull requests smaller than 50 lines...
This is not correct, it should be
❌ Try to keep pull requests smaller than 100 lines...

**Comment by muiriswoulfe** [comment] 2022-10-07 18:16
Thanks for clarifying @aerodynamica. I'll look to bring in a fix for this in the next release.

**Closed** 2022-10-19 14:12 UTC
Labels: bug
